// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lib2x3/graph/graph.proto

package graph

import (
	bytes "bytes"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// IsPrime specifies if a graph system has constituent factors or not.
// If a graph is prime, then it cannot be formed by combining any other particles.
type IsPrime int32

const (
	IsPrime_Unspecified IsPrime = 0
	IsPrime_Yes         IsPrime = 1
	IsPrime_No          IsPrime = 2
)

var IsPrime_name = map[int32]string{
	0: "IsPrime_Unspecified",
	1: "IsPrime_Yes",
	2: "IsPrime_No",
}

var IsPrime_value = map[string]int32{
	"IsPrime_Unspecified": 0,
	"IsPrime_Yes":         1,
	"IsPrime_No":          2,
}

func (IsPrime) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d0cecb80079ca5, []int{0}
}

// GroupID is a vertex group ID containing one or more Vtx.
type GroupID int32

const (
	GroupID_void      GroupID = 0
	GroupID_LoopVtx   GroupID = 1
	GroupID_LoopGroup GroupID = 2
	GroupID_G1        GroupID = 3
)

var GroupID_name = map[int32]string{
	0: "GroupID_void",
	1: "GroupID_LoopVtx",
	2: "GroupID_LoopGroup",
	3: "GroupID_G1",
}

var GroupID_value = map[string]int32{
	"GroupID_void":      0,
	"GroupID_LoopVtx":   1,
	"GroupID_LoopGroup": 2,
	"GroupID_G1":        3,
}

func (GroupID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d0cecb80079ca5, []int{1}
}

// VtxStatus specifies the current state of Vtx that comprise a 2x3 graph.
type VtxStatus int32

const (
	// The graph is an in unassigned or otherwise invalid state
	VtxStatus_Invalid VtxStatus = 0
	// All Vtx have been validated as expressing a valid and complete graph.
	// VtxID, E_FromVtx. E_Sign have been assigned.
	// Each Vtx is in its own separate group and has exactly 3 VtxEdges.
	VtxStatus_Validated VtxStatus = 2
	// First, edges are sorted by DstVtxID then SrcVtxID.
	// Next, edges that have matching DstVtxID and SrcVtxID are combined (summed).
	VtxStatus_Normalized VtxStatus = 4
	// A cycle spectrum is performed on the graph to canonically order vtx groups.
	// Vtx determined to be in the same group are merged into a single vtx group.
	// Finally, all edges are normalized.
	VtxStatus_Canonized VtxStatus = 6
)

var VtxStatus_name = map[int32]string{
	0: "VtxStatus_Invalid",
	2: "VtxStatus_Validated",
	4: "VtxStatus_Normalized",
	6: "VtxStatus_Canonized",
}

var VtxStatus_value = map[string]int32{
	"VtxStatus_Invalid":    0,
	"VtxStatus_Validated":  2,
	"VtxStatus_Normalized": 4,
	"VtxStatus_Canonized":  6,
}

func (VtxStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_23d0cecb80079ca5, []int{2}
}

type CatalogState struct {
	MajorVers int32 `protobuf:"varint,1,opt,name=MajorVers,proto3" json:"MajorVers,omitempty"`
	MinorVers int32 `protobuf:"varint,2,opt,name=MinorVers,proto3" json:"MinorVers,omitempty"`
	// TraceCount is the Traces len for this Catalog's Traces index.
	// This effectively sets a vertex size limit for Graphs this Catalog can process.
	// DefaultCatalogTraceCount specifies the default TraceCount for new catalogs.
	TraceCount int32 `protobuf:"varint,10,opt,name=TraceCount,proto3" json:"TraceCount,omitempty"`
	// NumTraces[Nv] is the number of traces of in this catalog for a given number of vertices.
	// Note: NumTraces[0] is always 0 and len(NumTraces) == TraceCount+1
	NumTraces []uint64 `protobuf:"varint,11,rep,packed,name=NumTraces,proto3" json:"NumTraces,omitempty"`
	// NumPrimes[Nv] is the number of particle primes for a given number of vertices.
	// Note: NumPrimes[0] is always 0 and len(NumPrimes) == TraceCount+1
	NumPrimes []uint64 `protobuf:"varint,12,rep,packed,name=NumPrimes,proto3" json:"NumPrimes,omitempty"`
	// Set if this catalog is to auto-determine if a newly added Graph / Traces are primes.
	IsPrimeCatalog bool `protobuf:"varint,20,opt,name=IsPrimeCatalog,proto3" json:"IsPrimeCatalog,omitempty"`
}

func (m *CatalogState) Reset()      { *m = CatalogState{} }
func (*CatalogState) ProtoMessage() {}
func (*CatalogState) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d0cecb80079ca5, []int{0}
}
func (m *CatalogState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CatalogState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CatalogState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CatalogState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CatalogState.Merge(m, src)
}
func (m *CatalogState) XXX_Size() int {
	return m.Size()
}
func (m *CatalogState) XXX_DiscardUnknown() {
	xxx_messageInfo_CatalogState.DiscardUnknown(m)
}

var xxx_messageInfo_CatalogState proto.InternalMessageInfo

func (m *CatalogState) GetMajorVers() int32 {
	if m != nil {
		return m.MajorVers
	}
	return 0
}

func (m *CatalogState) GetMinorVers() int32 {
	if m != nil {
		return m.MinorVers
	}
	return 0
}

func (m *CatalogState) GetTraceCount() int32 {
	if m != nil {
		return m.TraceCount
	}
	return 0
}

func (m *CatalogState) GetNumTraces() []uint64 {
	if m != nil {
		return m.NumTraces
	}
	return nil
}

func (m *CatalogState) GetNumPrimes() []uint64 {
	if m != nil {
		return m.NumPrimes
	}
	return nil
}

func (m *CatalogState) GetIsPrimeCatalog() bool {
	if m != nil {
		return m.IsPrimeCatalog
	}
	return false
}

// GraphDef is a particular vertex+edge assignment with bound names.
// Has similarities to a "Contributing structure" in quantum|chemistry lingo. https://en.wikipedia.org/wiki/Resonance_(chemistry)
type GraphDef struct {
	IsPrime IsPrime `protobuf:"varint,1,opt,name=IsPrime,proto3,enum=graph.IsPrime" json:"IsPrime,omitempty"`
	// If non-zero, the Traces of this graph has a registered ID.
	// These values can be used to lookup a graph's common ascii symbolic name, UTF8 symbolic name, or nickname
	TracesID uint64 `protobuf:"varint,2,opt,name=TracesID,proto3" json:"TracesID,omitempty"`
	GraphID  uint64 `protobuf:"varint,3,opt,name=GraphID,proto3" json:"GraphID,omitempty"`
	// A specific vertex+edge assignment
	GraphEncoding []byte `protobuf:"bytes,8,opt,name=GraphEncoding,proto3" json:"GraphEncoding,omitempty"`
	// Graph expr string that canonically express this graph and can therefore be used for easy graph equivalence testing.
	CanonicGraphExpr string `protobuf:"bytes,9,opt,name=CanonicGraphExpr,proto3" json:"CanonicGraphExpr,omitempty"`
	// Any number of graph expr strings that reduce to the same equivalent (canonic) graph.
	// This list is stored and maintained in sorted UTF8 order for binary search.
	GraphExprs []string `protobuf:"bytes,12,rep,name=GraphExprs,proto3" json:"GraphExprs,omitempty"`
}

func (m *GraphDef) Reset()      { *m = GraphDef{} }
func (*GraphDef) ProtoMessage() {}
func (*GraphDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d0cecb80079ca5, []int{1}
}
func (m *GraphDef) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GraphDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GraphDef.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GraphDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphDef.Merge(m, src)
}
func (m *GraphDef) XXX_Size() int {
	return m.Size()
}
func (m *GraphDef) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphDef.DiscardUnknown(m)
}

var xxx_messageInfo_GraphDef proto.InternalMessageInfo

func (m *GraphDef) GetIsPrime() IsPrime {
	if m != nil {
		return m.IsPrime
	}
	return IsPrime_Unspecified
}

func (m *GraphDef) GetTracesID() uint64 {
	if m != nil {
		return m.TracesID
	}
	return 0
}

func (m *GraphDef) GetGraphID() uint64 {
	if m != nil {
		return m.GraphID
	}
	return 0
}

func (m *GraphDef) GetGraphEncoding() []byte {
	if m != nil {
		return m.GraphEncoding
	}
	return nil
}

func (m *GraphDef) GetCanonicGraphExpr() string {
	if m != nil {
		return m.CanonicGraphExpr
	}
	return ""
}

func (m *GraphDef) GetGraphExprs() []string {
	if m != nil {
		return m.GraphExprs
	}
	return nil
}

// VtxEdge is characterized by the Src and Dst VtxID and C1 and C2.
// Identities that can transform one VtxEdge into another VtxEdge can be used in a process
//    called normalization where edge signs and degree are rotated to a canonical form.
//
// Working hypothesis:  any valid 2x3 graph expressed as a set of VtxEdges since normalizations of C1 and C2
//     are enough on their own to uniquely identify a graph.  Since the graph is known to exist and be a valid construction,.
//     by the given set ensures that C1 and C2 *alone* are enough to represent the graph (and thus reconstruct it if need be).
type VtxEdge struct {
	// Initially assigned label: 1, 2, 3, ..  (a one-based index ID)
	DstVtxID uint32 `protobuf:"varint,1,opt,name=DstVtxID,proto3" json:"DstVtxID,omitempty"`
	// Specifies the remote vertex of this edge (a one-based vtx index ID)
	SrcVtxID uint32 `protobuf:"varint,3,opt,name=SrcVtxID,proto3" json:"SrcVtxID,omitempty"`
	// Instances of vertex loops (self-edges)
	// Only non-zero when SrcVtxID == DstVtxID
	// The contribution to C1 is: C1_Pos + 0C1_Neg
	C1_Pos int32 `protobuf:"varint,8,opt,name=C1_Pos,json=C1Pos,proto3" json:"C1_Pos,omitempty"`
	C1_Neg int32 `protobuf:"varint,9,opt,name=C1_Neg,json=C1Neg,proto3" json:"C1_Neg,omitempty"`
	// Instances of a "characteristic 1" edge, which appears as either:
	//     - a single edge (positive or negative), or
	//     - a triple edge with signs (+,+,-) or (-,-,+)
	// The contribution to C2 is: 1 * (E1_Pos + E1_Neg)
	E1_Pos int32 `protobuf:"varint,12,opt,name=E1_Pos,json=E1Pos,proto3" json:"E1_Pos,omitempty"`
	E1_Neg int32 `protobuf:"varint,13,opt,name=E1_Neg,json=E1Neg,proto3" json:"E1_Neg,omitempty"`
	// Instances of a "characteristic 2" edges (a double edge, positive or negative)
	// The contribution to C2 is: 4 * (E2_Pos + E2_Neg)
	E2_Pos int32 `protobuf:"varint,14,opt,name=E2_Pos,json=E2Pos,proto3" json:"E2_Pos,omitempty"`
	E2_Neg int32 `protobuf:"varint,15,opt,name=E2_Neg,json=E2Neg,proto3" json:"E2_Neg,omitempty"`
}

func (m *VtxEdge) Reset()      { *m = VtxEdge{} }
func (*VtxEdge) ProtoMessage() {}
func (*VtxEdge) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d0cecb80079ca5, []int{2}
}
func (m *VtxEdge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VtxEdge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VtxEdge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VtxEdge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VtxEdge.Merge(m, src)
}
func (m *VtxEdge) XXX_Size() int {
	return m.Size()
}
func (m *VtxEdge) XXX_DiscardUnknown() {
	xxx_messageInfo_VtxEdge.DiscardUnknown(m)
}

var xxx_messageInfo_VtxEdge proto.InternalMessageInfo

func (m *VtxEdge) GetDstVtxID() uint32 {
	if m != nil {
		return m.DstVtxID
	}
	return 0
}

func (m *VtxEdge) GetSrcVtxID() uint32 {
	if m != nil {
		return m.SrcVtxID
	}
	return 0
}

func (m *VtxEdge) GetC1_Pos() int32 {
	if m != nil {
		return m.C1_Pos
	}
	return 0
}

func (m *VtxEdge) GetC1_Neg() int32 {
	if m != nil {
		return m.C1_Neg
	}
	return 0
}

func (m *VtxEdge) GetE1_Pos() int32 {
	if m != nil {
		return m.E1_Pos
	}
	return 0
}

func (m *VtxEdge) GetE1_Neg() int32 {
	if m != nil {
		return m.E1_Neg
	}
	return 0
}

func (m *VtxEdge) GetE2_Pos() int32 {
	if m != nil {
		return m.E2_Pos
	}
	return 0
}

func (m *VtxEdge) GetE2_Neg() int32 {
	if m != nil {
		return m.E2_Neg
	}
	return 0
}

// VtxGroup generally aren't used for Graph serialization but is used to model runtime processing and state
type VtxGroup struct {
	// Number of total Vtx instances in this group
	VtxCount uint32 `protobuf:"varint,1,opt,name=VtxCount,proto3" json:"VtxCount,omitempty"`
	// Group ID assignment of home Vtx based on canonic cycle vector comparison ordering.
	// 0 denotes unassigned; first valid GroupID is 1.
	GroupID uint32 `protobuf:"varint,3,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	// When assigned from a 2x3 graph, each Vtx has 3 edges.
	// After canonization, the edges of vertices having the same Cycles are consolidated into corresponding groups.
	Edges []*VtxEdge `protobuf:"bytes,5,rep,name=Edges,proto3" json:"Edges,omitempty"`
	// The product of this times VtxCount is the this groups total contribution to VtxGraph.Traces
	Cycles []int64 `protobuf:"varint,10,rep,packed,name=Cycles,proto3" json:"Cycles,omitempty"`
}

func (m *VtxGroup) Reset()      { *m = VtxGroup{} }
func (*VtxGroup) ProtoMessage() {}
func (*VtxGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d0cecb80079ca5, []int{3}
}
func (m *VtxGroup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VtxGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VtxGroup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VtxGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VtxGroup.Merge(m, src)
}
func (m *VtxGroup) XXX_Size() int {
	return m.Size()
}
func (m *VtxGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_VtxGroup.DiscardUnknown(m)
}

var xxx_messageInfo_VtxGroup proto.InternalMessageInfo

func (m *VtxGroup) GetVtxCount() uint32 {
	if m != nil {
		return m.VtxCount
	}
	return 0
}

func (m *VtxGroup) GetGroupID() uint32 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *VtxGroup) GetEdges() []*VtxEdge {
	if m != nil {
		return m.Edges
	}
	return nil
}

func (m *VtxGroup) GetCycles() []int64 {
	if m != nil {
		return m.Cycles
	}
	return nil
}

type Tag struct {
	Label  string `protobuf:"bytes,1,opt,name=Label,proto3" json:"Label,omitempty"`
	TagURI string `protobuf:"bytes,2,opt,name=TagURI,proto3" json:"TagURI,omitempty"`
	Expr   string `protobuf:"bytes,3,opt,name=Expr,proto3" json:"Expr,omitempty"`
}

func (m *Tag) Reset()      { *m = Tag{} }
func (*Tag) ProtoMessage() {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d0cecb80079ca5, []int{4}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return m.Size()
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Tag) GetTagURI() string {
	if m != nil {
		return m.TagURI
	}
	return ""
}

func (m *Tag) GetExpr() string {
	if m != nil {
		return m.Expr
	}
	return ""
}

type VtxGraph struct {
	Status VtxStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=graph.VtxStatus" json:"Status,omitempty"`
	Tags   []*Tag    `protobuf:"bytes,2,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Traces []int64   `protobuf:"varint,6,rep,packed,name=Traces,proto3" json:"Traces,omitempty"`
}

func (m *VtxGraph) Reset()      { *m = VtxGraph{} }
func (*VtxGraph) ProtoMessage() {}
func (*VtxGraph) Descriptor() ([]byte, []int) {
	return fileDescriptor_23d0cecb80079ca5, []int{5}
}
func (m *VtxGraph) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VtxGraph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VtxGraph.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VtxGraph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VtxGraph.Merge(m, src)
}
func (m *VtxGraph) XXX_Size() int {
	return m.Size()
}
func (m *VtxGraph) XXX_DiscardUnknown() {
	xxx_messageInfo_VtxGraph.DiscardUnknown(m)
}

var xxx_messageInfo_VtxGraph proto.InternalMessageInfo

func (m *VtxGraph) GetStatus() VtxStatus {
	if m != nil {
		return m.Status
	}
	return VtxStatus_Invalid
}

func (m *VtxGraph) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *VtxGraph) GetTraces() []int64 {
	if m != nil {
		return m.Traces
	}
	return nil
}

func init() {
	proto.RegisterEnum("graph.IsPrime", IsPrime_name, IsPrime_value)
	proto.RegisterEnum("graph.GroupID", GroupID_name, GroupID_value)
	proto.RegisterEnum("graph.VtxStatus", VtxStatus_name, VtxStatus_value)
	proto.RegisterType((*CatalogState)(nil), "graph.CatalogState")
	proto.RegisterType((*GraphDef)(nil), "graph.GraphDef")
	proto.RegisterType((*VtxEdge)(nil), "graph.VtxEdge")
	proto.RegisterType((*VtxGroup)(nil), "graph.VtxGroup")
	proto.RegisterType((*Tag)(nil), "graph.Tag")
	proto.RegisterType((*VtxGraph)(nil), "graph.VtxGraph")
}

func init() { proto.RegisterFile("lib2x3/graph/graph.proto", fileDescriptor_23d0cecb80079ca5) }

var fileDescriptor_23d0cecb80079ca5 = []byte{
	// 710 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x94, 0xdf, 0x6a, 0x22, 0x49,
	0x14, 0xc6, 0x2d, 0x5b, 0x8d, 0x9e, 0x18, 0xd3, 0x5b, 0x49, 0x36, 0xcd, 0xb2, 0x14, 0x22, 0x61,
	0x69, 0xbc, 0xc8, 0x12, 0xb3, 0x4f, 0xb0, 0x2a, 0x22, 0x64, 0x25, 0x54, 0x8c, 0xcb, 0x5e, 0x49,
	0x45, 0x2b, 0x9d, 0x5e, 0x4c, 0x57, 0xd3, 0xdd, 0x06, 0x77, 0x2f, 0x86, 0x79, 0x84, 0x79, 0x8c,
	0x79, 0x94, 0x81, 0x81, 0x21, 0x97, 0xb9, 0x98, 0x8b, 0x89, 0xb9, 0x99, 0xcb, 0x3c, 0xc2, 0x50,
	0xff, 0xda, 0x64, 0xe6, 0x46, 0xce, 0xf7, 0xfb, 0x4e, 0x95, 0xe7, 0x9c, 0xaa, 0x6a, 0xf0, 0x16,
	0xe1, 0x55, 0x67, 0x75, 0xfa, 0x7b, 0x90, 0xb0, 0xf8, 0x46, 0xff, 0x1e, 0xc7, 0x89, 0xc8, 0x04,
	0x2e, 0x2b, 0xd1, 0xfa, 0x84, 0xa0, 0xde, 0x65, 0x19, 0x5b, 0x88, 0xe0, 0x22, 0x63, 0x19, 0xc7,
	0xbf, 0x42, 0xed, 0x2f, 0xf6, 0xaf, 0x48, 0x26, 0x3c, 0x49, 0x3d, 0xd4, 0x44, 0x7e, 0x99, 0x6e,
	0x80, 0x72, 0xc3, 0xc8, 0xb8, 0x45, 0xe3, 0x5a, 0x80, 0x09, 0xc0, 0x38, 0x61, 0x33, 0xde, 0x15,
	0xcb, 0x28, 0xf3, 0x40, 0xd9, 0x2f, 0x88, 0x5c, 0x3d, 0x5a, 0xde, 0x2a, 0x90, 0x7a, 0xdb, 0x4d,
	0xc7, 0x2f, 0xd1, 0x0d, 0x30, 0xee, 0x79, 0x12, 0xde, 0xf2, 0xd4, 0xab, 0xe7, 0xae, 0x06, 0xf8,
	0x37, 0x68, 0x0c, 0x53, 0x15, 0x9b, 0x72, 0xbd, 0xfd, 0x26, 0xf2, 0xab, 0xf4, 0x3b, 0xda, 0xfa,
	0x8c, 0xa0, 0x3a, 0x90, 0xad, 0xf5, 0xf8, 0x35, 0xf6, 0x61, 0xcb, 0xd8, 0xaa, 0x95, 0x46, 0xa7,
	0x71, 0xac, 0x67, 0x60, 0x28, 0xb5, 0x36, 0xfe, 0x05, 0xaa, 0xba, 0x8c, 0x61, 0x4f, 0xf5, 0x55,
	0xa2, 0xb9, 0xc6, 0x1e, 0x6c, 0xa9, 0x1d, 0x87, 0x3d, 0xcf, 0x51, 0x96, 0x95, 0xf8, 0x08, 0x76,
	0x54, 0xd8, 0x8f, 0x66, 0x62, 0x1e, 0x46, 0x81, 0x57, 0x6d, 0x22, 0xbf, 0x4e, 0x5f, 0x43, 0xdc,
	0x06, 0xb7, 0xcb, 0x22, 0x11, 0x85, 0x33, 0xcd, 0x57, 0x71, 0xe2, 0xd5, 0x9a, 0xc8, 0xaf, 0xd1,
	0x1f, 0xb8, 0x1c, 0x61, 0x2e, 0xf4, 0x14, 0x6a, 0xf4, 0x05, 0x69, 0x7d, 0x44, 0xb0, 0x35, 0xc9,
	0x56, 0xfd, 0x79, 0xa0, 0x6a, 0xee, 0xa5, 0xd9, 0x24, 0x5b, 0x0d, 0x7b, 0xaa, 0xbd, 0x1d, 0x9a,
	0x6b, 0xe9, 0x5d, 0x24, 0x33, 0xed, 0x39, 0xda, 0xb3, 0x1a, 0x1f, 0x40, 0xa5, 0x7b, 0x32, 0x3d,
	0x17, 0xa9, 0x2a, 0xb7, 0x4c, 0xcb, 0xdd, 0x93, 0x73, 0x91, 0x1a, 0x3c, 0xe2, 0x81, 0x2a, 0x4e,
	0xe1, 0x11, 0x0f, 0x24, 0xee, 0xeb, 0xec, 0xba, 0xc6, 0x7d, 0x9b, 0xdd, 0xd7, 0xd9, 0x3b, 0x16,
	0xdb, 0xec, 0x8e, 0xca, 0x6e, 0x18, 0xdc, 0xb1, 0xd9, 0x1d, 0x95, 0xbd, 0x6b, 0xf1, 0x88, 0x07,
	0xad, 0x37, 0x50, 0x9d, 0x64, 0xab, 0x41, 0x22, 0x96, 0xb1, 0xac, 0x78, 0x92, 0xad, 0xf4, 0xd5,
	0x31, 0xdd, 0x58, 0xad, 0x4f, 0x40, 0x2c, 0xe3, 0xbc, 0x19, 0x2b, 0xf1, 0x11, 0x94, 0xe5, 0x2c,
	0x52, 0xaf, 0xdc, 0x74, 0xfc, 0xed, 0xfc, 0x7c, 0xcd, 0x88, 0xa8, 0x36, 0xf1, 0xcf, 0x50, 0xe9,
	0xfe, 0x37, 0x5b, 0xf0, 0xd4, 0x83, 0xa6, 0xe3, 0x3b, 0xd4, 0xa8, 0xd6, 0x00, 0x9c, 0x31, 0x0b,
	0xf0, 0x3e, 0x94, 0xcf, 0xd8, 0x15, 0x5f, 0xa8, 0xff, 0xad, 0x51, 0x2d, 0xe4, 0xa2, 0x31, 0x0b,
	0x2e, 0xe9, 0x50, 0x5d, 0x88, 0x1a, 0x35, 0x0a, 0x63, 0x28, 0xa9, 0x23, 0x74, 0x14, 0x55, 0x71,
	0x6b, 0x61, 0x1a, 0x61, 0xf1, 0x0d, 0xf6, 0xa1, 0x22, 0x9f, 0xd2, 0x32, 0x35, 0x77, 0xce, 0xdd,
	0xd4, 0xa4, 0x39, 0x35, 0x3e, 0x26, 0x50, 0x1a, 0xb3, 0x40, 0x3e, 0x24, 0x59, 0x3b, 0x98, 0xbc,
	0x31, 0x0b, 0xa8, 0xe2, 0xaa, 0x02, 0xfd, 0x58, 0x2a, 0xba, 0x6c, 0xad, 0xda, 0xdd, 0xfc, 0x5a,
	0xe3, 0x43, 0xd8, 0x33, 0xe1, 0xf4, 0x32, 0x4a, 0x63, 0x3e, 0x0b, 0xaf, 0x43, 0x3e, 0x77, 0x0b,
	0x78, 0x17, 0xb6, 0xad, 0xf1, 0x0f, 0x4f, 0x5d, 0x84, 0x1b, 0x00, 0x16, 0x8c, 0x84, 0x5b, 0x6c,
	0xff, 0x9d, 0xcf, 0x14, 0xbb, 0x50, 0x37, 0xe1, 0xf4, 0x4e, 0x84, 0x72, 0xf5, 0x1e, 0xec, 0x5a,
	0x72, 0x26, 0x44, 0x3c, 0xc9, 0x56, 0x2e, 0xc2, 0x07, 0xf0, 0xd3, 0x4b, 0xa8, 0x62, 0xb7, 0x28,
	0x37, 0xb6, 0x78, 0x70, 0xe2, 0x3a, 0xed, 0x08, 0x6a, 0x79, 0xab, 0x72, 0x4d, 0x2e, 0xa6, 0xc3,
	0xe8, 0x8e, 0x2d, 0xd4, 0xfe, 0x87, 0xb0, 0xb7, 0xc1, 0x13, 0x09, 0x59, 0xc6, 0xe7, 0x6e, 0x11,
	0x7b, 0xb0, 0xbf, 0x31, 0x46, 0x22, 0xb9, 0x65, 0x8b, 0xf0, 0x7f, 0x3e, 0x77, 0x4b, 0xaf, 0x97,
	0xe8, 0x77, 0x23, 0x8d, 0xca, 0x9f, 0x7f, 0xdc, 0x3f, 0x92, 0xc2, 0xc3, 0x23, 0x29, 0x3c, 0x3f,
	0x12, 0xf4, 0x76, 0x4d, 0xd0, 0xfb, 0x35, 0x41, 0x1f, 0xd6, 0x04, 0xdd, 0xaf, 0x09, 0xfa, 0xb2,
	0x26, 0xe8, 0xeb, 0x9a, 0x14, 0x9e, 0xd7, 0x04, 0xbd, 0x7b, 0x22, 0x85, 0xfb, 0x27, 0x52, 0x78,
	0x78, 0x22, 0x85, 0xab, 0x8a, 0xfa, 0x0c, 0x9e, 0x7e, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x0a,
	0x85, 0xa5, 0x22, 0x05, 0x00, 0x00,
}

func (x IsPrime) String() string {
	s, ok := IsPrime_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x GroupID) String() string {
	s, ok := GroupID_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x VtxStatus) String() string {
	s, ok := VtxStatus_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *CatalogState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CatalogState)
	if !ok {
		that2, ok := that.(CatalogState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MajorVers != that1.MajorVers {
		return false
	}
	if this.MinorVers != that1.MinorVers {
		return false
	}
	if this.TraceCount != that1.TraceCount {
		return false
	}
	if len(this.NumTraces) != len(that1.NumTraces) {
		return false
	}
	for i := range this.NumTraces {
		if this.NumTraces[i] != that1.NumTraces[i] {
			return false
		}
	}
	if len(this.NumPrimes) != len(that1.NumPrimes) {
		return false
	}
	for i := range this.NumPrimes {
		if this.NumPrimes[i] != that1.NumPrimes[i] {
			return false
		}
	}
	if this.IsPrimeCatalog != that1.IsPrimeCatalog {
		return false
	}
	return true
}
func (this *GraphDef) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GraphDef)
	if !ok {
		that2, ok := that.(GraphDef)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.IsPrime != that1.IsPrime {
		return false
	}
	if this.TracesID != that1.TracesID {
		return false
	}
	if this.GraphID != that1.GraphID {
		return false
	}
	if !bytes.Equal(this.GraphEncoding, that1.GraphEncoding) {
		return false
	}
	if this.CanonicGraphExpr != that1.CanonicGraphExpr {
		return false
	}
	if len(this.GraphExprs) != len(that1.GraphExprs) {
		return false
	}
	for i := range this.GraphExprs {
		if this.GraphExprs[i] != that1.GraphExprs[i] {
			return false
		}
	}
	return true
}
func (this *VtxEdge) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VtxEdge)
	if !ok {
		that2, ok := that.(VtxEdge)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.DstVtxID != that1.DstVtxID {
		return false
	}
	if this.SrcVtxID != that1.SrcVtxID {
		return false
	}
	if this.C1_Pos != that1.C1_Pos {
		return false
	}
	if this.C1_Neg != that1.C1_Neg {
		return false
	}
	if this.E1_Pos != that1.E1_Pos {
		return false
	}
	if this.E1_Neg != that1.E1_Neg {
		return false
	}
	if this.E2_Pos != that1.E2_Pos {
		return false
	}
	if this.E2_Neg != that1.E2_Neg {
		return false
	}
	return true
}
func (this *VtxGroup) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VtxGroup)
	if !ok {
		that2, ok := that.(VtxGroup)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.VtxCount != that1.VtxCount {
		return false
	}
	if this.GroupID != that1.GroupID {
		return false
	}
	if len(this.Edges) != len(that1.Edges) {
		return false
	}
	for i := range this.Edges {
		if !this.Edges[i].Equal(that1.Edges[i]) {
			return false
		}
	}
	if len(this.Cycles) != len(that1.Cycles) {
		return false
	}
	for i := range this.Cycles {
		if this.Cycles[i] != that1.Cycles[i] {
			return false
		}
	}
	return true
}
func (this *Tag) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Tag)
	if !ok {
		that2, ok := that.(Tag)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Label != that1.Label {
		return false
	}
	if this.TagURI != that1.TagURI {
		return false
	}
	if this.Expr != that1.Expr {
		return false
	}
	return true
}
func (this *VtxGraph) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VtxGraph)
	if !ok {
		that2, ok := that.(VtxGraph)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if len(this.Tags) != len(that1.Tags) {
		return false
	}
	for i := range this.Tags {
		if !this.Tags[i].Equal(that1.Tags[i]) {
			return false
		}
	}
	if len(this.Traces) != len(that1.Traces) {
		return false
	}
	for i := range this.Traces {
		if this.Traces[i] != that1.Traces[i] {
			return false
		}
	}
	return true
}
func (this *CatalogState) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&graph.CatalogState{")
	s = append(s, "MajorVers: "+fmt.Sprintf("%#v", this.MajorVers)+",\n")
	s = append(s, "MinorVers: "+fmt.Sprintf("%#v", this.MinorVers)+",\n")
	s = append(s, "TraceCount: "+fmt.Sprintf("%#v", this.TraceCount)+",\n")
	s = append(s, "NumTraces: "+fmt.Sprintf("%#v", this.NumTraces)+",\n")
	s = append(s, "NumPrimes: "+fmt.Sprintf("%#v", this.NumPrimes)+",\n")
	s = append(s, "IsPrimeCatalog: "+fmt.Sprintf("%#v", this.IsPrimeCatalog)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GraphDef) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&graph.GraphDef{")
	s = append(s, "IsPrime: "+fmt.Sprintf("%#v", this.IsPrime)+",\n")
	s = append(s, "TracesID: "+fmt.Sprintf("%#v", this.TracesID)+",\n")
	s = append(s, "GraphID: "+fmt.Sprintf("%#v", this.GraphID)+",\n")
	s = append(s, "GraphEncoding: "+fmt.Sprintf("%#v", this.GraphEncoding)+",\n")
	s = append(s, "CanonicGraphExpr: "+fmt.Sprintf("%#v", this.CanonicGraphExpr)+",\n")
	s = append(s, "GraphExprs: "+fmt.Sprintf("%#v", this.GraphExprs)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *VtxEdge) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 12)
	s = append(s, "&graph.VtxEdge{")
	s = append(s, "DstVtxID: "+fmt.Sprintf("%#v", this.DstVtxID)+",\n")
	s = append(s, "SrcVtxID: "+fmt.Sprintf("%#v", this.SrcVtxID)+",\n")
	s = append(s, "C1_Pos: "+fmt.Sprintf("%#v", this.C1_Pos)+",\n")
	s = append(s, "C1_Neg: "+fmt.Sprintf("%#v", this.C1_Neg)+",\n")
	s = append(s, "E1_Pos: "+fmt.Sprintf("%#v", this.E1_Pos)+",\n")
	s = append(s, "E1_Neg: "+fmt.Sprintf("%#v", this.E1_Neg)+",\n")
	s = append(s, "E2_Pos: "+fmt.Sprintf("%#v", this.E2_Pos)+",\n")
	s = append(s, "E2_Neg: "+fmt.Sprintf("%#v", this.E2_Neg)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *VtxGroup) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&graph.VtxGroup{")
	s = append(s, "VtxCount: "+fmt.Sprintf("%#v", this.VtxCount)+",\n")
	s = append(s, "GroupID: "+fmt.Sprintf("%#v", this.GroupID)+",\n")
	if this.Edges != nil {
		s = append(s, "Edges: "+fmt.Sprintf("%#v", this.Edges)+",\n")
	}
	s = append(s, "Cycles: "+fmt.Sprintf("%#v", this.Cycles)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Tag) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&graph.Tag{")
	s = append(s, "Label: "+fmt.Sprintf("%#v", this.Label)+",\n")
	s = append(s, "TagURI: "+fmt.Sprintf("%#v", this.TagURI)+",\n")
	s = append(s, "Expr: "+fmt.Sprintf("%#v", this.Expr)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *VtxGraph) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&graph.VtxGraph{")
	s = append(s, "Status: "+fmt.Sprintf("%#v", this.Status)+",\n")
	if this.Tags != nil {
		s = append(s, "Tags: "+fmt.Sprintf("%#v", this.Tags)+",\n")
	}
	s = append(s, "Traces: "+fmt.Sprintf("%#v", this.Traces)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringGraph(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *CatalogState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CatalogState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CatalogState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsPrimeCatalog {
		i--
		if m.IsPrimeCatalog {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if len(m.NumPrimes) > 0 {
		dAtA2 := make([]byte, len(m.NumPrimes)*10)
		var j1 int
		for _, num := range m.NumPrimes {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintGraph(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x62
	}
	if len(m.NumTraces) > 0 {
		dAtA4 := make([]byte, len(m.NumTraces)*10)
		var j3 int
		for _, num := range m.NumTraces {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintGraph(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x5a
	}
	if m.TraceCount != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.TraceCount))
		i--
		dAtA[i] = 0x50
	}
	if m.MinorVers != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.MinorVers))
		i--
		dAtA[i] = 0x10
	}
	if m.MajorVers != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.MajorVers))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GraphDef) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GraphDef) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GraphDef) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GraphExprs) > 0 {
		for iNdEx := len(m.GraphExprs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.GraphExprs[iNdEx])
			copy(dAtA[i:], m.GraphExprs[iNdEx])
			i = encodeVarintGraph(dAtA, i, uint64(len(m.GraphExprs[iNdEx])))
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.CanonicGraphExpr) > 0 {
		i -= len(m.CanonicGraphExpr)
		copy(dAtA[i:], m.CanonicGraphExpr)
		i = encodeVarintGraph(dAtA, i, uint64(len(m.CanonicGraphExpr)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.GraphEncoding) > 0 {
		i -= len(m.GraphEncoding)
		copy(dAtA[i:], m.GraphEncoding)
		i = encodeVarintGraph(dAtA, i, uint64(len(m.GraphEncoding)))
		i--
		dAtA[i] = 0x42
	}
	if m.GraphID != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.GraphID))
		i--
		dAtA[i] = 0x18
	}
	if m.TracesID != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.TracesID))
		i--
		dAtA[i] = 0x10
	}
	if m.IsPrime != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.IsPrime))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VtxEdge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VtxEdge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VtxEdge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.E2_Neg != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.E2_Neg))
		i--
		dAtA[i] = 0x78
	}
	if m.E2_Pos != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.E2_Pos))
		i--
		dAtA[i] = 0x70
	}
	if m.E1_Neg != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.E1_Neg))
		i--
		dAtA[i] = 0x68
	}
	if m.E1_Pos != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.E1_Pos))
		i--
		dAtA[i] = 0x60
	}
	if m.C1_Neg != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.C1_Neg))
		i--
		dAtA[i] = 0x48
	}
	if m.C1_Pos != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.C1_Pos))
		i--
		dAtA[i] = 0x40
	}
	if m.SrcVtxID != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.SrcVtxID))
		i--
		dAtA[i] = 0x18
	}
	if m.DstVtxID != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.DstVtxID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VtxGroup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VtxGroup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VtxGroup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Cycles) > 0 {
		dAtA6 := make([]byte, len(m.Cycles)*10)
		var j5 int
		for _, num1 := range m.Cycles {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA6[j5] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j5++
			}
			dAtA6[j5] = uint8(num)
			j5++
		}
		i -= j5
		copy(dAtA[i:], dAtA6[:j5])
		i = encodeVarintGraph(dAtA, i, uint64(j5))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Edges) > 0 {
		for iNdEx := len(m.Edges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Edges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGraph(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.GroupID != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.GroupID))
		i--
		dAtA[i] = 0x18
	}
	if m.VtxCount != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.VtxCount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Tag) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tag) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Tag) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Expr) > 0 {
		i -= len(m.Expr)
		copy(dAtA[i:], m.Expr)
		i = encodeVarintGraph(dAtA, i, uint64(len(m.Expr)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TagURI) > 0 {
		i -= len(m.TagURI)
		copy(dAtA[i:], m.TagURI)
		i = encodeVarintGraph(dAtA, i, uint64(len(m.TagURI)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Label) > 0 {
		i -= len(m.Label)
		copy(dAtA[i:], m.Label)
		i = encodeVarintGraph(dAtA, i, uint64(len(m.Label)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VtxGraph) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VtxGraph) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VtxGraph) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Traces) > 0 {
		dAtA8 := make([]byte, len(m.Traces)*10)
		var j7 int
		for _, num1 := range m.Traces {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA8[j7] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j7++
			}
			dAtA8[j7] = uint8(num)
			j7++
		}
		i -= j7
		copy(dAtA[i:], dAtA8[:j7])
		i = encodeVarintGraph(dAtA, i, uint64(j7))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Tags) > 0 {
		for iNdEx := len(m.Tags) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tags[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGraph(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Status != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGraph(dAtA []byte, offset int, v uint64) int {
	offset -= sovGraph(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CatalogState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MajorVers != 0 {
		n += 1 + sovGraph(uint64(m.MajorVers))
	}
	if m.MinorVers != 0 {
		n += 1 + sovGraph(uint64(m.MinorVers))
	}
	if m.TraceCount != 0 {
		n += 1 + sovGraph(uint64(m.TraceCount))
	}
	if len(m.NumTraces) > 0 {
		l = 0
		for _, e := range m.NumTraces {
			l += sovGraph(uint64(e))
		}
		n += 1 + sovGraph(uint64(l)) + l
	}
	if len(m.NumPrimes) > 0 {
		l = 0
		for _, e := range m.NumPrimes {
			l += sovGraph(uint64(e))
		}
		n += 1 + sovGraph(uint64(l)) + l
	}
	if m.IsPrimeCatalog {
		n += 3
	}
	return n
}

func (m *GraphDef) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsPrime != 0 {
		n += 1 + sovGraph(uint64(m.IsPrime))
	}
	if m.TracesID != 0 {
		n += 1 + sovGraph(uint64(m.TracesID))
	}
	if m.GraphID != 0 {
		n += 1 + sovGraph(uint64(m.GraphID))
	}
	l = len(m.GraphEncoding)
	if l > 0 {
		n += 1 + l + sovGraph(uint64(l))
	}
	l = len(m.CanonicGraphExpr)
	if l > 0 {
		n += 1 + l + sovGraph(uint64(l))
	}
	if len(m.GraphExprs) > 0 {
		for _, s := range m.GraphExprs {
			l = len(s)
			n += 1 + l + sovGraph(uint64(l))
		}
	}
	return n
}

func (m *VtxEdge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DstVtxID != 0 {
		n += 1 + sovGraph(uint64(m.DstVtxID))
	}
	if m.SrcVtxID != 0 {
		n += 1 + sovGraph(uint64(m.SrcVtxID))
	}
	if m.C1_Pos != 0 {
		n += 1 + sovGraph(uint64(m.C1_Pos))
	}
	if m.C1_Neg != 0 {
		n += 1 + sovGraph(uint64(m.C1_Neg))
	}
	if m.E1_Pos != 0 {
		n += 1 + sovGraph(uint64(m.E1_Pos))
	}
	if m.E1_Neg != 0 {
		n += 1 + sovGraph(uint64(m.E1_Neg))
	}
	if m.E2_Pos != 0 {
		n += 1 + sovGraph(uint64(m.E2_Pos))
	}
	if m.E2_Neg != 0 {
		n += 1 + sovGraph(uint64(m.E2_Neg))
	}
	return n
}

func (m *VtxGroup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VtxCount != 0 {
		n += 1 + sovGraph(uint64(m.VtxCount))
	}
	if m.GroupID != 0 {
		n += 1 + sovGraph(uint64(m.GroupID))
	}
	if len(m.Edges) > 0 {
		for _, e := range m.Edges {
			l = e.Size()
			n += 1 + l + sovGraph(uint64(l))
		}
	}
	if len(m.Cycles) > 0 {
		l = 0
		for _, e := range m.Cycles {
			l += sovGraph(uint64(e))
		}
		n += 1 + sovGraph(uint64(l)) + l
	}
	return n
}

func (m *Tag) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Label)
	if l > 0 {
		n += 1 + l + sovGraph(uint64(l))
	}
	l = len(m.TagURI)
	if l > 0 {
		n += 1 + l + sovGraph(uint64(l))
	}
	l = len(m.Expr)
	if l > 0 {
		n += 1 + l + sovGraph(uint64(l))
	}
	return n
}

func (m *VtxGraph) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovGraph(uint64(m.Status))
	}
	if len(m.Tags) > 0 {
		for _, e := range m.Tags {
			l = e.Size()
			n += 1 + l + sovGraph(uint64(l))
		}
	}
	if len(m.Traces) > 0 {
		l = 0
		for _, e := range m.Traces {
			l += sovGraph(uint64(e))
		}
		n += 1 + sovGraph(uint64(l)) + l
	}
	return n
}

func sovGraph(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGraph(x uint64) (n int) {
	return sovGraph(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *CatalogState) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CatalogState{`,
		`MajorVers:` + fmt.Sprintf("%v", this.MajorVers) + `,`,
		`MinorVers:` + fmt.Sprintf("%v", this.MinorVers) + `,`,
		`TraceCount:` + fmt.Sprintf("%v", this.TraceCount) + `,`,
		`NumTraces:` + fmt.Sprintf("%v", this.NumTraces) + `,`,
		`NumPrimes:` + fmt.Sprintf("%v", this.NumPrimes) + `,`,
		`IsPrimeCatalog:` + fmt.Sprintf("%v", this.IsPrimeCatalog) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GraphDef) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GraphDef{`,
		`IsPrime:` + fmt.Sprintf("%v", this.IsPrime) + `,`,
		`TracesID:` + fmt.Sprintf("%v", this.TracesID) + `,`,
		`GraphID:` + fmt.Sprintf("%v", this.GraphID) + `,`,
		`GraphEncoding:` + fmt.Sprintf("%v", this.GraphEncoding) + `,`,
		`CanonicGraphExpr:` + fmt.Sprintf("%v", this.CanonicGraphExpr) + `,`,
		`GraphExprs:` + fmt.Sprintf("%v", this.GraphExprs) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VtxEdge) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VtxEdge{`,
		`DstVtxID:` + fmt.Sprintf("%v", this.DstVtxID) + `,`,
		`SrcVtxID:` + fmt.Sprintf("%v", this.SrcVtxID) + `,`,
		`C1_Pos:` + fmt.Sprintf("%v", this.C1_Pos) + `,`,
		`C1_Neg:` + fmt.Sprintf("%v", this.C1_Neg) + `,`,
		`E1_Pos:` + fmt.Sprintf("%v", this.E1_Pos) + `,`,
		`E1_Neg:` + fmt.Sprintf("%v", this.E1_Neg) + `,`,
		`E2_Pos:` + fmt.Sprintf("%v", this.E2_Pos) + `,`,
		`E2_Neg:` + fmt.Sprintf("%v", this.E2_Neg) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VtxGroup) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForEdges := "[]*VtxEdge{"
	for _, f := range this.Edges {
		repeatedStringForEdges += strings.Replace(f.String(), "VtxEdge", "VtxEdge", 1) + ","
	}
	repeatedStringForEdges += "}"
	s := strings.Join([]string{`&VtxGroup{`,
		`VtxCount:` + fmt.Sprintf("%v", this.VtxCount) + `,`,
		`GroupID:` + fmt.Sprintf("%v", this.GroupID) + `,`,
		`Edges:` + repeatedStringForEdges + `,`,
		`Cycles:` + fmt.Sprintf("%v", this.Cycles) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Tag) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Tag{`,
		`Label:` + fmt.Sprintf("%v", this.Label) + `,`,
		`TagURI:` + fmt.Sprintf("%v", this.TagURI) + `,`,
		`Expr:` + fmt.Sprintf("%v", this.Expr) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VtxGraph) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForTags := "[]*Tag{"
	for _, f := range this.Tags {
		repeatedStringForTags += strings.Replace(f.String(), "Tag", "Tag", 1) + ","
	}
	repeatedStringForTags += "}"
	s := strings.Join([]string{`&VtxGraph{`,
		`Status:` + fmt.Sprintf("%v", this.Status) + `,`,
		`Tags:` + repeatedStringForTags + `,`,
		`Traces:` + fmt.Sprintf("%v", this.Traces) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGraph(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *CatalogState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraph
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CatalogState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CatalogState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MajorVers", wireType)
			}
			m.MajorVers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MajorVers |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinorVers", wireType)
			}
			m.MinorVers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinorVers |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceCount", wireType)
			}
			m.TraceCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TraceCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraph
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.NumTraces = append(m.NumTraces, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraph
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGraph
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGraph
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.NumTraces) == 0 {
					m.NumTraces = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGraph
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.NumTraces = append(m.NumTraces, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field NumTraces", wireType)
			}
		case 12:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraph
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.NumPrimes = append(m.NumPrimes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraph
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGraph
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGraph
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.NumPrimes) == 0 {
					m.NumPrimes = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGraph
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.NumPrimes = append(m.NumPrimes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field NumPrimes", wireType)
			}
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsPrimeCatalog", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsPrimeCatalog = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGraph(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGraph
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GraphDef) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraph
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GraphDef: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GraphDef: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsPrime", wireType)
			}
			m.IsPrime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IsPrime |= IsPrime(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TracesID", wireType)
			}
			m.TracesID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TracesID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GraphID", wireType)
			}
			m.GraphID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GraphID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GraphEncoding", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGraph
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGraph
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GraphEncoding = append(m.GraphEncoding[:0], dAtA[iNdEx:postIndex]...)
			if m.GraphEncoding == nil {
				m.GraphEncoding = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanonicGraphExpr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGraph
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGraph
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CanonicGraphExpr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GraphExprs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGraph
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGraph
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GraphExprs = append(m.GraphExprs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGraph(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGraph
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VtxEdge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraph
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VtxEdge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VtxEdge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DstVtxID", wireType)
			}
			m.DstVtxID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DstVtxID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcVtxID", wireType)
			}
			m.SrcVtxID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SrcVtxID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field C1_Pos", wireType)
			}
			m.C1_Pos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.C1_Pos |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field C1_Neg", wireType)
			}
			m.C1_Neg = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.C1_Neg |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field E1_Pos", wireType)
			}
			m.E1_Pos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.E1_Pos |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field E1_Neg", wireType)
			}
			m.E1_Neg = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.E1_Neg |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field E2_Pos", wireType)
			}
			m.E2_Pos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.E2_Pos |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field E2_Neg", wireType)
			}
			m.E2_Neg = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.E2_Neg |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGraph(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGraph
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VtxGroup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraph
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VtxGroup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VtxGroup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VtxCount", wireType)
			}
			m.VtxCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VtxCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupID", wireType)
			}
			m.GroupID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroupID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Edges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGraph
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGraph
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Edges = append(m.Edges, &VtxEdge{})
			if err := m.Edges[len(m.Edges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraph
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Cycles = append(m.Cycles, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraph
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGraph
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGraph
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Cycles) == 0 {
					m.Cycles = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGraph
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Cycles = append(m.Cycles, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Cycles", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGraph(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGraph
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Tag) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraph
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Tag: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Tag: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Label", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGraph
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGraph
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Label = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TagURI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGraph
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGraph
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TagURI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGraph
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGraph
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Expr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGraph(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGraph
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VtxGraph) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraph
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VtxGraph: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VtxGraph: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= VtxStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGraph
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGraph
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tags = append(m.Tags, &Tag{})
			if err := m.Tags[len(m.Tags)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraph
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Traces = append(m.Traces, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraph
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGraph
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGraph
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Traces) == 0 {
					m.Traces = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGraph
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Traces = append(m.Traces, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Traces", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGraph(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGraph
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGraph(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGraph
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGraph
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGraph
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGraph
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGraph        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGraph          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGraph = fmt.Errorf("proto: unexpected end of group")
)
