// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lib2x3/graph/graph.proto

package graph

import (
	bytes "bytes"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// IsPrime specifies if a graph system has constituent factors or not.
// If a graph is prime, then it cannot be formed by combining any other particles.
type IsPrime int32

const (
	IsPrime_Unspecified IsPrime = 0
	IsPrime_Yes         IsPrime = 1
	IsPrime_No          IsPrime = 2
)

var IsPrime_name = map[int32]string{
	0: "IsPrime_Unspecified",
	1: "IsPrime_Yes",
	2: "IsPrime_No",
}

var IsPrime_value = map[string]int32{
	"IsPrime_Unspecified": 0,
	"IsPrime_Yes":         1,
	"IsPrime_No":          2,
}

func (IsPrime) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b4d17ed8b6c319b2, []int{0}
}

type CatalogState struct {
	MajorVers int32 `protobuf:"varint,1,opt,name=MajorVers,proto3" json:"MajorVers,omitempty"`
	MinorVers int32 `protobuf:"varint,2,opt,name=MinorVers,proto3" json:"MinorVers,omitempty"`
	// TraceCount is the Traces len for this Catalog's Traces index.
	// This effectively sets a vertex size limit for Graphs this Catalog can process.
	// DefaultCatalogTraceCount specifies the default TraceCount for new catalogs.
	TraceCount int32 `protobuf:"varint,10,opt,name=TraceCount,proto3" json:"TraceCount,omitempty"`
	// NumTraces[Nv] is the number of traces of in this catalog for a given number of vertices.
	// Note: NumTraces[0] is always 0 and len(NumTraces) == TraceCount+1
	NumTraces []uint64 `protobuf:"varint,11,rep,packed,name=NumTraces,proto3" json:"NumTraces,omitempty"`
	// NumPrimes[Nv] is the number of particle primes for a given number of vertices.
	// Note: NumPrimes[0] is always 0 and len(NumPrimes) == TraceCount+1
	NumPrimes []uint64 `protobuf:"varint,12,rep,packed,name=NumPrimes,proto3" json:"NumPrimes,omitempty"`
	// Set if this catalog is to auto-determine if a newly added Graph / Traces are primes.
	IsPrimeCatalog bool `protobuf:"varint,20,opt,name=IsPrimeCatalog,proto3" json:"IsPrimeCatalog,omitempty"`
}

func (m *CatalogState) Reset()      { *m = CatalogState{} }
func (*CatalogState) ProtoMessage() {}
func (*CatalogState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4d17ed8b6c319b2, []int{0}
}
func (m *CatalogState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CatalogState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CatalogState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CatalogState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CatalogState.Merge(m, src)
}
func (m *CatalogState) XXX_Size() int {
	return m.Size()
}
func (m *CatalogState) XXX_DiscardUnknown() {
	xxx_messageInfo_CatalogState.DiscardUnknown(m)
}

var xxx_messageInfo_CatalogState proto.InternalMessageInfo

func (m *CatalogState) GetMajorVers() int32 {
	if m != nil {
		return m.MajorVers
	}
	return 0
}

func (m *CatalogState) GetMinorVers() int32 {
	if m != nil {
		return m.MinorVers
	}
	return 0
}

func (m *CatalogState) GetTraceCount() int32 {
	if m != nil {
		return m.TraceCount
	}
	return 0
}

func (m *CatalogState) GetNumTraces() []uint64 {
	if m != nil {
		return m.NumTraces
	}
	return nil
}

func (m *CatalogState) GetNumPrimes() []uint64 {
	if m != nil {
		return m.NumPrimes
	}
	return nil
}

func (m *CatalogState) GetIsPrimeCatalog() bool {
	if m != nil {
		return m.IsPrimeCatalog
	}
	return false
}

// GraphDef is a particular vertex+edge assignment with bound names.
// Has similarities to a "Contributing structure" in quantum|chemistry lingo. https://en.wikipedia.org/wiki/Resonance_(chemistry)
type GraphDef struct {
	IsPrime IsPrime `protobuf:"varint,1,opt,name=IsPrime,proto3,enum=graph.IsPrime" json:"IsPrime,omitempty"`
	// If non-zero, the Traces of this graph has a registered ID.
	// These values can be used to lookup a graph's common ascii symbolic name, UTF8 symbolic name, or nickname
	TracesID uint64 `protobuf:"varint,2,opt,name=TracesID,proto3" json:"TracesID,omitempty"`
	GraphID  uint64 `protobuf:"varint,3,opt,name=GraphID,proto3" json:"GraphID,omitempty"`
	// A specific vertex+edge assignment
	GraphEncoding []byte `protobuf:"bytes,8,opt,name=GraphEncoding,proto3" json:"GraphEncoding,omitempty"`
}

func (m *GraphDef) Reset()      { *m = GraphDef{} }
func (*GraphDef) ProtoMessage() {}
func (*GraphDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4d17ed8b6c319b2, []int{1}
}
func (m *GraphDef) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GraphDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GraphDef.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GraphDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphDef.Merge(m, src)
}
func (m *GraphDef) XXX_Size() int {
	return m.Size()
}
func (m *GraphDef) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphDef.DiscardUnknown(m)
}

var xxx_messageInfo_GraphDef proto.InternalMessageInfo

func (m *GraphDef) GetIsPrime() IsPrime {
	if m != nil {
		return m.IsPrime
	}
	return IsPrime_Unspecified
}

func (m *GraphDef) GetTracesID() uint64 {
	if m != nil {
		return m.TracesID
	}
	return 0
}

func (m *GraphDef) GetGraphID() uint64 {
	if m != nil {
		return m.GraphID
	}
	return 0
}

func (m *GraphDef) GetGraphEncoding() []byte {
	if m != nil {
		return m.GraphEncoding
	}
	return nil
}

func init() {
	proto.RegisterEnum("graph.IsPrime", IsPrime_name, IsPrime_value)
	proto.RegisterType((*CatalogState)(nil), "graph.CatalogState")
	proto.RegisterType((*GraphDef)(nil), "graph.GraphDef")
}

func init() { proto.RegisterFile("lib2x3/graph/graph.proto", fileDescriptor_b4d17ed8b6c319b2) }

var fileDescriptor_b4d17ed8b6c319b2 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcd, 0x4e, 0xea, 0x40,
	0x14, 0xc7, 0x7b, 0xf8, 0xb8, 0xf4, 0x1e, 0xb8, 0xbd, 0x64, 0x34, 0x71, 0x62, 0xcc, 0x49, 0x43,
	0x8c, 0x69, 0x5c, 0x60, 0x02, 0x3e, 0x81, 0x60, 0x0c, 0x0b, 0x89, 0xa9, 0x1f, 0x89, 0x2b, 0x53,
	0x60, 0xc0, 0x1a, 0x68, 0x49, 0x5b, 0x12, 0x97, 0x3e, 0x02, 0x8f, 0xe1, 0xa3, 0xb8, 0x32, 0x2c,
	0x59, 0x4a, 0xd9, 0xb8, 0xe4, 0x11, 0x0c, 0xd3, 0x29, 0xa8, 0x9b, 0xe6, 0x9c, 0xdf, 0x2f, 0x9d,
	0xfc, 0xff, 0x33, 0xc8, 0x87, 0x6e, 0xa7, 0xfe, 0x5c, 0x3b, 0x19, 0x04, 0xce, 0xf8, 0x31, 0xf9,
	0x56, 0xc7, 0x81, 0x1f, 0xf9, 0x2c, 0x2f, 0x97, 0xca, 0x3b, 0x60, 0xa9, 0xe1, 0x44, 0xce, 0xd0,
	0x1f, 0x5c, 0x47, 0x4e, 0x24, 0xd8, 0x01, 0xfe, 0xbd, 0x74, 0x9e, 0xfc, 0xe0, 0x4e, 0x04, 0x21,
	0x07, 0x13, 0xac, 0xbc, 0xbd, 0x05, 0xd2, 0xba, 0x9e, 0xb2, 0x19, 0x65, 0x53, 0xc0, 0x08, 0xf1,
	0x26, 0x70, 0xba, 0xa2, 0xe1, 0x4f, 0xbc, 0x88, 0xa3, 0xd4, 0xdf, 0xc8, 0xfa, 0xef, 0xf6, 0x64,
	0x24, 0x41, 0xc8, 0x8b, 0x66, 0xd6, 0xca, 0xd9, 0x5b, 0xa0, 0xec, 0x55, 0xe0, 0x8e, 0x44, 0xc8,
	0x4b, 0x1b, 0x9b, 0x00, 0x76, 0x84, 0x46, 0x2b, 0x94, 0xb3, 0x8a, 0xcb, 0x77, 0x4d, 0xb0, 0x74,
	0xfb, 0x17, 0xad, 0x4c, 0x01, 0xf5, 0x8b, 0x75, 0xb5, 0xa6, 0xe8, 0x33, 0x0b, 0x0b, 0x4a, 0xcb,
	0x2a, 0x46, 0xcd, 0xa8, 0x26, 0x77, 0xa0, 0xa8, 0x9d, 0x6a, 0xb6, 0x8f, 0x7a, 0x12, 0xa3, 0xd5,
	0x94, 0xbd, 0x72, 0xf6, 0x66, 0x67, 0x1c, 0x0b, 0xf2, 0xc4, 0x56, 0x93, 0x67, 0xa5, 0x4a, 0x57,
	0x76, 0x88, 0xff, 0xe4, 0x78, 0xee, 0x75, 0xfd, 0x9e, 0xeb, 0x0d, 0xb8, 0x6e, 0x82, 0x55, 0xb2,
	0x7f, 0xc2, 0xe3, 0xc6, 0x26, 0x05, 0xdb, 0xc3, 0x1d, 0x35, 0x3e, 0xdc, 0x7a, 0xe1, 0x58, 0x74,
	0xdd, 0xbe, 0x2b, 0x7a, 0x65, 0x8d, 0xfd, 0xc7, 0x62, 0x2a, 0xee, 0x45, 0x58, 0x06, 0x66, 0x20,
	0xa6, 0xa0, 0xed, 0x97, 0x33, 0x67, 0xa7, 0xb3, 0x05, 0x69, 0xf3, 0x05, 0x69, 0xab, 0x05, 0xc1,
	0x4b, 0x4c, 0xf0, 0x1a, 0x13, 0xbc, 0xc5, 0x04, 0xb3, 0x98, 0xe0, 0x23, 0x26, 0xf8, 0x8c, 0x49,
	0x5b, 0xc5, 0x04, 0xd3, 0x25, 0x69, 0xb3, 0x25, 0x69, 0xf3, 0x25, 0x69, 0x9d, 0x3f, 0xf2, 0xb1,
	0xeb, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x47, 0xc4, 0xd5, 0x21, 0x08, 0x02, 0x00, 0x00,
}

func (x IsPrime) String() string {
	s, ok := IsPrime_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *CatalogState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CatalogState)
	if !ok {
		that2, ok := that.(CatalogState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MajorVers != that1.MajorVers {
		return false
	}
	if this.MinorVers != that1.MinorVers {
		return false
	}
	if this.TraceCount != that1.TraceCount {
		return false
	}
	if len(this.NumTraces) != len(that1.NumTraces) {
		return false
	}
	for i := range this.NumTraces {
		if this.NumTraces[i] != that1.NumTraces[i] {
			return false
		}
	}
	if len(this.NumPrimes) != len(that1.NumPrimes) {
		return false
	}
	for i := range this.NumPrimes {
		if this.NumPrimes[i] != that1.NumPrimes[i] {
			return false
		}
	}
	if this.IsPrimeCatalog != that1.IsPrimeCatalog {
		return false
	}
	return true
}
func (this *GraphDef) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GraphDef)
	if !ok {
		that2, ok := that.(GraphDef)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.IsPrime != that1.IsPrime {
		return false
	}
	if this.TracesID != that1.TracesID {
		return false
	}
	if this.GraphID != that1.GraphID {
		return false
	}
	if !bytes.Equal(this.GraphEncoding, that1.GraphEncoding) {
		return false
	}
	return true
}
func (this *CatalogState) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&graph.CatalogState{")
	s = append(s, "MajorVers: "+fmt.Sprintf("%#v", this.MajorVers)+",\n")
	s = append(s, "MinorVers: "+fmt.Sprintf("%#v", this.MinorVers)+",\n")
	s = append(s, "TraceCount: "+fmt.Sprintf("%#v", this.TraceCount)+",\n")
	s = append(s, "NumTraces: "+fmt.Sprintf("%#v", this.NumTraces)+",\n")
	s = append(s, "NumPrimes: "+fmt.Sprintf("%#v", this.NumPrimes)+",\n")
	s = append(s, "IsPrimeCatalog: "+fmt.Sprintf("%#v", this.IsPrimeCatalog)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GraphDef) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&graph.GraphDef{")
	s = append(s, "IsPrime: "+fmt.Sprintf("%#v", this.IsPrime)+",\n")
	s = append(s, "TracesID: "+fmt.Sprintf("%#v", this.TracesID)+",\n")
	s = append(s, "GraphID: "+fmt.Sprintf("%#v", this.GraphID)+",\n")
	s = append(s, "GraphEncoding: "+fmt.Sprintf("%#v", this.GraphEncoding)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringGraph(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *CatalogState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CatalogState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CatalogState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsPrimeCatalog {
		i--
		if m.IsPrimeCatalog {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if len(m.NumPrimes) > 0 {
		dAtA2 := make([]byte, len(m.NumPrimes)*10)
		var j1 int
		for _, num := range m.NumPrimes {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintGraph(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x62
	}
	if len(m.NumTraces) > 0 {
		dAtA4 := make([]byte, len(m.NumTraces)*10)
		var j3 int
		for _, num := range m.NumTraces {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintGraph(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x5a
	}
	if m.TraceCount != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.TraceCount))
		i--
		dAtA[i] = 0x50
	}
	if m.MinorVers != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.MinorVers))
		i--
		dAtA[i] = 0x10
	}
	if m.MajorVers != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.MajorVers))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GraphDef) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GraphDef) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GraphDef) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GraphEncoding) > 0 {
		i -= len(m.GraphEncoding)
		copy(dAtA[i:], m.GraphEncoding)
		i = encodeVarintGraph(dAtA, i, uint64(len(m.GraphEncoding)))
		i--
		dAtA[i] = 0x42
	}
	if m.GraphID != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.GraphID))
		i--
		dAtA[i] = 0x18
	}
	if m.TracesID != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.TracesID))
		i--
		dAtA[i] = 0x10
	}
	if m.IsPrime != 0 {
		i = encodeVarintGraph(dAtA, i, uint64(m.IsPrime))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGraph(dAtA []byte, offset int, v uint64) int {
	offset -= sovGraph(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CatalogState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MajorVers != 0 {
		n += 1 + sovGraph(uint64(m.MajorVers))
	}
	if m.MinorVers != 0 {
		n += 1 + sovGraph(uint64(m.MinorVers))
	}
	if m.TraceCount != 0 {
		n += 1 + sovGraph(uint64(m.TraceCount))
	}
	if len(m.NumTraces) > 0 {
		l = 0
		for _, e := range m.NumTraces {
			l += sovGraph(uint64(e))
		}
		n += 1 + sovGraph(uint64(l)) + l
	}
	if len(m.NumPrimes) > 0 {
		l = 0
		for _, e := range m.NumPrimes {
			l += sovGraph(uint64(e))
		}
		n += 1 + sovGraph(uint64(l)) + l
	}
	if m.IsPrimeCatalog {
		n += 3
	}
	return n
}

func (m *GraphDef) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsPrime != 0 {
		n += 1 + sovGraph(uint64(m.IsPrime))
	}
	if m.TracesID != 0 {
		n += 1 + sovGraph(uint64(m.TracesID))
	}
	if m.GraphID != 0 {
		n += 1 + sovGraph(uint64(m.GraphID))
	}
	l = len(m.GraphEncoding)
	if l > 0 {
		n += 1 + l + sovGraph(uint64(l))
	}
	return n
}

func sovGraph(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGraph(x uint64) (n int) {
	return sovGraph(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *CatalogState) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CatalogState{`,
		`MajorVers:` + fmt.Sprintf("%v", this.MajorVers) + `,`,
		`MinorVers:` + fmt.Sprintf("%v", this.MinorVers) + `,`,
		`TraceCount:` + fmt.Sprintf("%v", this.TraceCount) + `,`,
		`NumTraces:` + fmt.Sprintf("%v", this.NumTraces) + `,`,
		`NumPrimes:` + fmt.Sprintf("%v", this.NumPrimes) + `,`,
		`IsPrimeCatalog:` + fmt.Sprintf("%v", this.IsPrimeCatalog) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GraphDef) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GraphDef{`,
		`IsPrime:` + fmt.Sprintf("%v", this.IsPrime) + `,`,
		`TracesID:` + fmt.Sprintf("%v", this.TracesID) + `,`,
		`GraphID:` + fmt.Sprintf("%v", this.GraphID) + `,`,
		`GraphEncoding:` + fmt.Sprintf("%v", this.GraphEncoding) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGraph(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *CatalogState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraph
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CatalogState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CatalogState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MajorVers", wireType)
			}
			m.MajorVers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MajorVers |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinorVers", wireType)
			}
			m.MinorVers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinorVers |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceCount", wireType)
			}
			m.TraceCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TraceCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraph
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.NumTraces = append(m.NumTraces, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraph
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGraph
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGraph
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.NumTraces) == 0 {
					m.NumTraces = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGraph
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.NumTraces = append(m.NumTraces, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field NumTraces", wireType)
			}
		case 12:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraph
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.NumPrimes = append(m.NumPrimes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGraph
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGraph
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGraph
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.NumPrimes) == 0 {
					m.NumPrimes = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGraph
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.NumPrimes = append(m.NumPrimes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field NumPrimes", wireType)
			}
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsPrimeCatalog", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsPrimeCatalog = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGraph(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGraph
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GraphDef) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGraph
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GraphDef: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GraphDef: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsPrime", wireType)
			}
			m.IsPrime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IsPrime |= IsPrime(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TracesID", wireType)
			}
			m.TracesID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TracesID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GraphID", wireType)
			}
			m.GraphID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GraphID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GraphEncoding", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGraph
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGraph
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GraphEncoding = append(m.GraphEncoding[:0], dAtA[iNdEx:postIndex]...)
			if m.GraphEncoding == nil {
				m.GraphEncoding = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGraph(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGraph
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGraph(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGraph
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGraph
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGraph
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGraph
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGraph
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGraph        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGraph          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGraph = fmt.Errorf("proto: unexpected end of group")
)
